name: ewallet_clover
description: Ewallet mobile application

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  sliding_up_panel: ^1.0.2 # Modal Bottom Sheet
  intl: ^0.16.1 # Number Formatter
  provider: ^4.3.3 # state management
  pinput: ^1.0.0 # pin input
  http: ^0.12.2 # Service/API request
  encrypt: ^3.2.0 # encrypt & decrypt
  flutter_svg: ^0.19.1 # For displaying SVG
  flutter_secure_storage: ^3.3.5 # Stores user in a secure storage | min sdk 18
  device_info_plus: ^0.7.2 # get device info
  shortuuid: ^2.1.1 # for shorter uuid generation
  qr_flutter: ^3.2.0 # used to generate qr code
  barcode_scan: ^3.0.1 # used to scan qr code
  local_auth: ^0.6.3+4 # biometrics
  flutter_launcher_icons: ^0.7.4 # App Icon

flutter_icons:
  android: "digiwallet_icon"
  ios: true
  image_path: "assets/images/digiwallet_icon.jpg"


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/svg/
